### ISSUE TITLE
[QUESTION] Improve Visual Studio workflow...

### ISSUE THREAD

**Issue by moebiussurfing** [mhtvsSFrpHdE/prefetch#5]
Hello @mhtvsSFrpHdE ,

EDIT: sorry, now I have seen this link: 
https://github.com/mhtvsSFrpHdE/prefetch/wiki/Frequently-asked-questions

I have discovered recently some tools like Primocache and Ultra RAMDisk, and this repo too.
What do you think about these other alternatives pro/cons vs this prefetch repo?

My intention is to speed up a bit my Visual Studio workflow.

Some VS files are located on c:/program files, and usually the project files are in another location, and the framework/libs you are using somewhere else...
Then, the RAM disk way I am not sure that could help here, 
because the files are not in the same folder, 
or maybe we don't want to include many folders that could make too bigger for the available RAM memory.

What do you think about a good approach to start think the workflow?

Thanks for the repo!
Regards

**Comment by mhtvsSFrpHdE** [comment]
A SSHD layer will provide you: frequency read disk sectors, save on two different I/O device.  
The SSD one faster than HDD one, so you just boot PC and expect most thing read from the SSD one.  
**WITH THIS SOLUTION**, you can enter working status by waiting less than 1 minute.

A file can take multiple sectors to save, but only part of this file is really often used:  
SSHD only cache these sectors and ignore other parts of this file.  
That's why you can use 12 GB SSHD to speed up a 60 GB database.

For example, in PrimoCache you include C:\ D:\ E:\, 3 different HDD partition in same L2 cache configuration.

`m/prefetch` don't/can't utilize your SSD without install other SSHD layer at same time,  
it just simulates you opened that program many times.  
You can do a test: Boot PC, open a program(slow), close, open again(faster), close, open again(fastest).  
This because the operating system keep recently read file in **IDLE RAM**.  
The problem is, OS don't do that for you automatically, for an unknown reason(blame Microsoft).

**WITH THIS SOLUTION**, you may, must wait 1~3 minute before you can enter working status.  
Because during cache process, all files still only save on HDD and not yet cached to RAM.  
This one also require you have enough IDLE RAM for this purpose.  
If you use ReSharper or TabNine, you soon discover your physical RAM usage is 7800 MB / 8192 MB:  
In this case, use prefetch is wasting of time because you have no IDLE RAM to hold file cache.

While I'm writing this, I open task manager and check my memory:  
In use 7.2 GB, Available 24.5 GB, Cached 6.3 GB.  
Firefox itself takes less than 1 GB, `1 GB < 24.5 GB true`,  
so its program file will fit to **IDLE RAM** without waste.

`m/prefetch` will print cache time:
```
Idle, Time: 45.60 Sec
Prefetching...
Idle, Time: 01.32 Sec
Prefetching...
Idle, Time: 01.03 Sec
Prefetching...
Idle, Time: 01.06 Sec
```
You can see the 2nd and future cache takes only 1 second,  
once this value greater than 1 second, for example 30 second or even 40 second,  
you will know your **IDLE RAM** is exhausted. In this case, go with SSHD.  
They don't require **IDLE RAM** to work.

**Comment by mhtvsSFrpHdE** [comment]
You can use "symbol link", first put all file copy to RAMDisk,  
then create symbol link from where these file is used:

```
// copy files to RAMDisk and save image to prevent lose
R:\include
R:\include\w32api.h
R:\include\malloc.h
...
```

```
cd /d "C:\x86_64-w64-mingw32"

// Delete exist
rd /s /q include

mklink /d include "R:\include"
```

Then you can use these file as usual from `C:\x86_64-w64-mingw32\include`,  
but OS will go to RAMDisk to find them, this is fast.

I don't recommend this solution, reason already explained in FAQ.  
SSHD and `m/prefetch` are designed to automated, but this one... not.

**Comment by mhtvsSFrpHdE** [comment]
Why there's so much choice? Because money.  
When I build my PC, I choose large RAM setup, but WD Blue 5400 RPM 2 TB.  
I can't afford something like Intel NVMe 2 TB, everyone knows it's fast.

You can buy one and putting everything into it, but if you don't,  
then you can only afford a 120 GB or 12 GB (Intel Optane),  
they are small, so you can't put all your stuff into it.

And we discovered we must take 150 GB space, but only 8 GB of them are used every day.  
SSHD is use your small SSD to cache these 8 GB and left others in HDD.

Furthermore, you don't even buy a SSD, but you have some idle RAM,  
`m/prefetch` is for this situation.

**Comment by moebiussurfing** [comment]
Thank you so much for your detailed reply.
I need to read it again carefully...

I have 32gb of RAM and a fast a 1tb fast m2, with Windows and all the Visual Studio files and projects.
I would like to check if Visual Studio and maybe Firefox/Brave can be a bit optimized.

**Comment by mhtvsSFrpHdE** [comment]
> Thank you so much for your detailed reply. I need to read it again carefully...
> 
> I have 32gb of RAM and a fast a 1tb fast m2, with Windows and all the Visual Studio files and projects. I would like to check if Visual Studio and maybe Firefox/Brave can be a bit optimized.

If you can handle it (don't care about SSD NAND consume), install all your stuff into SSD,  
and source code, compile output also SSD.  
If you must put things into certain partition path like `D:\`, use symbol link to redirect them to SSD.

Use SSD to hold everything is the fastest solution.

Or you can use part of the SSD to boost exist HDD partition(PrimoCache).

Load program files from SSD or from cached system RAM usually won't give you a noticeable different.

If you don't use SSD, here are some latest discovery might useful: https://github.com/mhtvsSFrpHdE/prefetch/issues/6
