### ISSUE TITLE
I don't quite understand how to use it

### ISSUE THREAD

**Issue by AndreyRGW** [mhtvsSFrpHdE/prefetch#51]
Hi! I'm interested in your program. I tried to set it to cache rimword in the ini file, but it doesn't seem to work (or I'm doing something wrong). Can you record a video guide on how to use prefetch for programs other than firefox? 

p.s. reading your wiki, I found a mention of file ParseProcmonLog.py but I do not see it in the 4.0.1 release

![image](https://user-images.githubusercontent.com/50556416/202800348-52a34a17-26e3-4349-9657-1ea64ef6ce50.png)

upd1: Found ParseProcmonLog.py
upd2: Still don't understand how to make it work.

**Comment by mhtvsSFrpHdE** [comment]
By my imagination, user first look at [main page](https://github.com/mhtvsSFrpHdE/prefetch) then:

1. [How to use](https://github.com/mhtvsSFrpHdE/prefetch#how-to-use)
2. [prefetch.ini](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini)
3. [PrefetchFolder](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini#prefetchfolder---array)

PrefetchFolder Literally says what folder you want to prefetch.  
Example:

```
[PrefetchFolder]
FirefoxAppData=C:\\\Mozilla\\AppData
FirefoxProgramFiles=C:\\Mozilla\\Program Files
```

4. [ExcludeFolder](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini#excludefolder---array)

Literally says what folder you **DON NOT** want to prefetch.

5. [PriorityIncludePattern](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini#priorityincludepattern---array)

When you still want to include certain files from already excluded folders.

Start with simple, this config will get you a at least work instance,  
by remove all values from ExcludeFolder and PriorityIncludePattern,  
the two is used to set advanced rules instead of prefetch anything.

```
[PrefetchFolder]
FirefoxAppData=C:\\\Mozilla\\AppData
FirefoxProgramFiles=C:\\Mozilla\\Program Files
[ExcludeFolder]
[PriorityIncludePattern]
```

6. About "FirefoxAppData" and "FirefoxProgramFiles"

See [array](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini#array) wiki, key name is not matter,  
it just requires unique key name to let program know how many values out there.

7. [ParseProcmonLog.py](https://github.com/mhtvsSFrpHdE/prefetch/wiki/Best-practice)

This additional program is used to set more advanced rules, because one discovered powerful of regex.  
You may need to familiar the basic (step 2~5), then go advanced.

**Comment by mhtvsSFrpHdE** [comment]
Download of [ParseProcmonLog.py](https://github.com/mhtvsSFrpHdE/prefetch/blob/master/qpp/prefetch/Tool/ParseProcmonLog.py)

ParseProcmonLog method is way too complex for public people who not an experienced programmer.  
For example, the relationship between python, program exe, logs, systeminternals, filter...

However, gifted people will magically utilize it without any education.  
I do forget to mention where did I put the file.

**Comment by mhtvsSFrpHdE** [comment]
Some settings are way too basic to forget to document them:
- [ ] PrefetchFolder
- [ ] ExcludeFolder
- [ ] PriorityIncludePattern

And:
- [ ] Fix: Forget to mention download of ParseProcmonLog.py

**Comment by AndreyRGW** [comment]
Hello, 
So, after I removed everything from ExcludeFolder and PriorityIncludePattern, prefetch seems to work. First, it scanned the folder for 5 seconds, and then 11.8 seconds of prefetching went on. During these 11.8 seconds, prefetch was loading the disk by 30-40%. After the prefetching was finished, I decided to run the rimworld, but I don't think I saw any difference in loading speed. Is this supposed to be like this, or did I do something wrong again? 
![image](https://user-images.githubusercontent.com/50556416/202853141-cd33c34b-6f97-489a-af51-3f48b0ed35d2.png)

**Comment by AndreyRGW** [comment]
Probably caused by : libstdc++-6.dll ( libstdc___6!ZN9__gnu_cxx27__verbose_terminate_handlerEv+18d )

Windbg ^
----------------------------------------
QObject::killTimers: timers cannot be stopped from another thread
terminate called after throwing an instance of 'std::bad_alloc'
terminate called recursively
what(): std::bad_alloc
Program "[15092] prefetch.exe" program ended with code 3 (0x3).

VC22 ^

**Comment by mhtvsSFrpHdE** [comment]
## Disk usage not go to 100%
Windows 10 task manager "Process" tab show disk usage of all disk device.  
For example, if you got 2 disk, then one disk maximum will be 50%.  
Go to "Performance" tab, and click one of the disk,  
this time, disk usage is accurate.

If disk usage still not go to 100%, try increase thread numbers:

```
[Thread]
MaxThreadCount=16
```

Default is your CPU cores, if you have a dual core cpu, default 0 means 2.  
If you have hyper thread enabled, default 0 means 4.  
The value is still low, some disk can handle more thread, so they go to 100% usage.  
Thread value target is 100% and no more,   
for example, 8 thread is 96%, 9 thread is 100%, then do not go 10 thread.

## No difference in loading speed
You spend 5.59+11.8 seconds on all files of RimWorldWin64 by not filter them.  
For example, my Firefox instance takes 53.2+55.67 seconds to scan and load.  
That means:
- You've got a high performance disk
- RimWorldWin64 is a relative small size game
- The game well packaged its resource, 4K random read is reduced
  (A well packaged game could reduce its ACL overhead, so scan take no time)

Compare to a game, Firefox drop dll, config, and database everywhere,  
each of them usually don't greater than 1 MB.  
Remember that sequence read are not bottleneck of a HDD, but random read is.

Look at the task manager during game loading,  
you should notice that disk usage should always be 0%.  
Because resource are already in RAM.  
In this case, CPU decompress resource speed is the bottleneck.  
You may need a better CPU.

## prefetch.cache.ini
This file is used to cache scan result, so you don't go through file tree at 2nd time.  
When you go through file tree to list all file, ACL is the maximum overhead so it can be slow.  
ACL is operating system need to confirm do you have the permission to even know the file exist.  
Instead, with a cache, you get the file directly without run ACL to know exist.

## User interface
There is similar relationship in software world, be like:
- `7z GUI` and `7za`, `tar`
- `GitHub Desktop` and `git`
- `Windows file explorer` and `dir`, `ls`

The project has no development team, I must choose the style of "do less to do more".  
So the program have relative good API to let you write your own GUI or inject additional feature.  
For example, compile as a console application and use python or something to send text to stdin interface.

The program crash directly with no error check is a side effect,  
I simply not possible to predict any potential bug.

## Dashes crash
#52 new issue created, it should be solved once I plan to code.  
I know it's critical, but I can't take action immediately.

Since you have the source code, you can add some code to `read_thread.cpp`.  
Look at line 37 `bool ReadThread::run_SearchExclude()`,  
Add an extra check, if `filePath` contains `-`, return true to skip this file.

However, because this is a crash, you may need to use Qt debugger,  
and LAST_KNOWN_POSITION macro to find real crash point.

## QTimer warning
#53 new issue created, but I think when QTimer warning is print,  
the program already crashed. QTimer must be destroyed by the operating system.  
During normal run, this message should not show.

## Compile in 64 bit
Unless you have a >= 3.5 GB file to prefetch, x64 only run slower in my imagination.  
Prefetch most deal with random read files which often smaller than 1 MB.

64 bit is a compiler issue, if you use correct compiler, you can get 64 bit exe.  
Not require to modifying source code.  
I've also not include Linux compile, although it's possible to run on Linux.

Compare to do anything personally, I prefer to leave the possibility to let people do their interest.

## Folders with many files
Did the program crash? Or just run slow.  
It's normal to slow when folder and files amount go large.  
That's how an HDD is slow, and how NTFS slow in ACL overhead.  
Prefetch itself already try to use multi thread.

**Comment by AndreyRGW** [comment]
> ## Folders with many files
> Did the program crash? Or just run slow. It's normal to slow when folder and files amount go large. That's how an HDD is slow, and how NTFS slow in ACL overhead. Prefetch itself already try to use multi thread.
> 
> Prefetch is utilize the time while you are not using PC. For example, you power on the computer, then go to breakfast, when you're back, files are already in RAM, although they did take 2+ minutes to load.

Yes, the program crashed, and my guess is that it's because of the large number of files (although I could be wrong since when I prefetch rimworld there were 48306 lines in the prefetch.cache.ini file) because prefetch crashes when I scan the folder with the stable diffusion neural network and the folder with my anaconda virtual environments. 

I am using Windows 11, Ryzen 5 5600X, GTX 1660 6GB GDDR5 10Ghz, 32 GB DDR4 Ram CL16.

**Comment by mhtvsSFrpHdE** [comment]
Holy[beep], I never imagined such a program can be useful when you are trying to machine learning AI on HDD.  
But it makes sense.

To debug, I have few ideas:
- Look at these file, if one of them >= 3.5 GB, use a x64 build, this is 32 bit out of memory
- You've mentioned when path contains "-", it will crash
- Too many files beyond limitations of QT ini file
- Too many files beyond limitations of C++ int (2147483647)

You may also 7-zip your problem folder and prefetch config,  
send them to me via BitTorrent, Mega online storage, OneDrive share, Syncthing, or anything you familiar with.

**Comment by mhtvsSFrpHdE** [comment]
Folders with many files crash issue created #56, related discussion go to that issue.

Path contains "-" crash issue created #52, related discussion go to that issue.

Lacking document issue created #54, related discussion go to that issue.

**Comment by AndreyRGW** [comment]
> * You've mentioned when path contains "-", it will crash

About that, it was just a coincidence. Since my stable diffusion folder was called "stable-diffusion-webui", I thought it might be the "-", but no, after I removed all the dashes by renaming the folder, the program kept crashing.


> You may also 7-zip your problem folder and prefetch config, send them to me via BitTorrent, Mega online storage, OneDrive share, Syncthing, or anything you familiar with.

Well, there might be a problem with that. I can send the prefetch folder, but the Stable Diffusion neural network folder weighs 39.7GB and anaconda weighs 75.5GB.

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW Then Syncthing is the only choce.  
Share your folder to Syncthing address `P3JPFOT-AGSUKMA-SO3MUHN-DJOLHDJ-7UBNI3G-XEL3XST-UUBTR4K-VRUABQQ`  
You can continue to use these folders without compress them to take twice space.

This address is 7x24 online, once you open Syncthing, transfer will begin and keep update.

**Comment by AndreyRGW** [comment]
@mhtvsSFrpHdE I think I sent it

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW I don't see a request, go to Syncthing web management UI:
1. "Add Remove Device"
2. Type address to "Device ID"
3. Give a nickname to "Device Name"
4. You can now click on your folder, Edit, Sharing, Check the device just added
5. Wait until I confirm request

**Comment by AndreyRGW** [comment]
@mhtvsSFrpHdE I made a torrent file, I think it will be faster that way.
[Anaconda3.zip](https://github.com/mhtvsSFrpHdE/prefetch/files/10056478/Anaconda3.zip)

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW I don't see there is a speed problem with Syncthing, cross-country network just be like that.

**Comment by AndreyRGW** [comment]
> @AndreyRGW I don't see there is a speed problem with Syncthing, cross-country network just be like that.

Ah, ok.

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW With BT, you can only push a bunch of files at a time, but Syncthing allow delta update, it basically is "Sync" software, work like OneDrive, but decentralized. So I can get future file updates without download another giant torrent.

**Comment by AndreyRGW** [comment]
Minidump created by windows
[prefetch.exe.11076.zip](https://github.com/mhtvsSFrpHdE/prefetch/files/10057076/prefetch.exe.11076.zip)

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW Look like the Connection Type is Relay right now, if you have dedicated IP, try forward 22000 port TCP and UDP.  
Or if you don't, I have a private relay server doesn't limit speed (public relay often come with anti abuse)

Settings, Connections, Sync Protocol Listen Addresses, paste the following text and OK
`tcp://0.0.0.0:22000, quic://0.0.0.0:22000, relay://i.americansdyg.com:22067/?id=BBX4JOK-SVMV7Z7-SBF7TAN-JUXEXRP-WXAIAOU-YJG5NMS-T6YTMW3-QF3WTQT&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=`

**Comment by AndreyRGW** [comment]
@mhtvsSFrpHdE  I don't have a dedicated ip. And with these settings I get i/o timeout.

**Comment by mhtvsSFrpHdE** [comment]
> @mhtvsSFrpHdE I don't have a dedicated ip. And with these settings I get i/o timeout.

I check the relay server, it's just updated it's address. Domain TTL is 40 minutes, and I just connected to new address.  
You can use `nslookup -debug i.americansdyg.com`, and you'll know when you will get new address.

```
    ANSWERS:
    ->  i.americansdyg.com
        canonical name = americansdyg.oicp.net
        ttl = 2321 (38 mins 41 secs)    // <- here
```

When this counter go to 0, new address will arrived.

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW Oh, I see it begins!

**Comment by mhtvsSFrpHdE** [comment]
@AndreyRGW If you can confirm "-" in path is not the problem, then obvious this is 32 bit out of ram.  

A not yet completed download `~syncthing~wd-v1-3-float32.ckpt.tmp` is `3.97 GB`.  
`~syncthing~torch_cuda_cu.dll.tmp` is `885 MB`.  
`~syncthing~torch_cuda.dll.tmp` is `833 MB`.

Prefetch use multi thread, that means it has the possibility to acquire 3.97 GB + 885 MB + 833 MB,  
total 5.64 GB, x64 is necessary.

I think 4.0.2 or above build will provide x64, I just not thought of this possibility before.

**Comment by mhtvsSFrpHdE** [comment]
Or I may add a buffer, read 100 MB each time, instead of load the entire file.

**Comment by mhtvsSFrpHdE** [comment]
> ![image](https://user-images.githubusercontent.com/50556416/203103540-386ac80e-0986-401f-a8b0-e133abdb8567.png)
> 
> What if I turn on large address aware?

I don't think that will work in your scenario.  
I just see a new file created, `~syncthing~model.ckpt.tmp` is `3.97` GB too.  
If this file goes into prefetch with `~syncthing~wd-v1-3-float32.ckpt.tmp`,  
maximum ram usage can go up to 7.94 GB.

That option may only allow you to not crash at 3.75 GB, 32 bit default is crash at 2 GB.

**Comment by AndreyRGW** [comment]
> > ![image](https://user-images.githubusercontent.com/50556416/203103540-386ac80e-0986-401f-a8b0-e133abdb8567.png)
> > What if I turn on large address aware?
> 
> I don't think that will work in your scenario. I just see a new file created, `~syncthing~model.ckpt.tmp` is `3.97` GB too. If this file goes into prefetch with `~syncthing~wd-v1-3-float32.ckpt.tmp`, maximum ram usage can go up to 7.94 GB.
> 
> That option may only allow you to not crash at 3.75 GB, 32 bit default is crash at 2 GB.

 I see. I will wait for 64bit version then)

**Comment by mhtvsSFrpHdE** [comment]
By the way, prefetch can't magically speed up all of your 108 GB files.  
It just accesses these files once, so they will reserve in RAM by operating system.  
Look at your task manager, Performance, Memory,  
There are value named "Available" and "Cached".

- Available
  How much **IDLE RAM** can be used as cache
- Cached
  How much file already in RAM, our mission is to move file from disk to cached
  Cached will never be greater than Available

108 GB is greater than 32 GB. If you have 22 GB available at the time,  
after prefetch done, only last 22 GB of 108 GB will remains in RAM.  
Others just be overrides between each other.  
Haven't considered if your AI program eats 24 GB, you end up with only 8 GB available.

That's why filter rules comes in. They help you pick up most slow files.  
For an HDD, they basically are small random files.  
For example, `plugin-container.exe` is `297 KB`, `AccessibleHandler.dll` is `180 KB`.

Your RimWorldWin64 did small enough to load entire to RAM, though.

**Comment by AndreyRGW** [comment]
> 108 GB is greater than 32 GB. If you have 22 GB available at the time, after prefetch done, only last 22 GB of 108 GB will remains in RAM. 

Actually, the main files I wanted to add to prefetch in total weigh 12GB, so in theory, my 32GB of RAM should be enough.
