### ISSUE TITLE
RAM Cache content wil be updated if the original file rewritten?

### ISSUE THREAD

**Issue by cutesniper22** [mhtvsSFrpHdE/prefetch#55]
As per titled... will the cache still functioning if original content changed or updated?

**Comment by mhtvsSFrpHdE** [comment]
I don't know how Windows deal with rewritten.  
By my experience, modified file stay in RAM for a while instead of erase immediately.

You will notice that software like VMware workstation,  
when you hibernate a virtual machine, 4~8 GB written to disk.  
However, if you continue the virtual machine immediately,  
they recover in just few seconds, instead of read entire hibernate file.

In this case, reboot host os or erase cache manually, you will notice that  
Windows will read all 4~8 GB from disk, which is much slower.

No need to worry about anyway, each time a prefetch interval is reached,  
your files always guaranteed to be up-to-date.

**Comment by mhtvsSFrpHdE** [comment]
I found these in my email box, but not see them in github issue.

> Possible to save ram cache content & re-use for next reboot? (Issue #55)
> I plan to set the "prefetch" cmd & run in task scheduler for every reboot & login. So it will auto load into ram without manual pump-in. My question is will this take long time to load into ram if I pump in more than 10-20GB cache into ram during startup/login process?

## Save ram cache content & re-use
Your description is unclear.

if: Write to faster storage media like SSD, to speed up first load  
This is can't be done without a true SSHD solution.  
See [compare to other solutions](https://github.com/mhtvsSFrpHdE/prefetch/wiki/FAQ_Compare-to-other-solutions) for more details.

if: Save scanned prefetch file list so after reboot you don't need to re-scan
This feature was already done called prefetch.cache.ini

if: Run at startup/login
You can use start menu, search for "run", type `shell:startup` and click OK,  
a folder will show, create a shortcut in this folder and you have a new startup item.  
For example, right click hold `prefetch.exe` drag into this folder window and release,  
choose "create shortcut".

## Time
You will find the answer in prefetch's idle timer.  
Prefetch will report how long it takes to execute a prefetch.

However, consider you have that much file,  
some of them may >= 3.5 GB per file, so you need to compile a x64 build,  
or the program is possible to out-of-memory crash in theory.
