### ISSUE TITLE
Prefetch 4.0.3 - Command line arguments not working

### ISSUE THREAD

**Issue by manciuszz** [mhtvsSFrpHdE/prefetch#59]
I've tested the version 4.0.3 and the loading of custom settings using the command line arguments seem to not give me any results.

**prefetch.exe test.ini**
**prefetch_performance.exe test.ini**
**prefetch_verbose.exe test.ini**
...
**prefetch.exe "test.ini"**

... Nothing seem to have any effect - the process just closes by itself immediately upon launch.

All .ini files during testing were stored near the executable files and stored inside C:\ drive so the full path contains no spaces.

Launching programs without arguments look for 'prefetch.ini' and does, indeed, work fine if it exists.

**Tested on Windows 11 Pro 25231 build**.

**Comment by mhtvsSFrpHdE** [comment]
@manciuszz I personally don't use this feature, so it does lack test.

Recently, my landlord unilaterally broke the agreement. Move place is required.  
Maybe during the next 1 or 2 weeks, I can't take action.

As a temporary solution, you can unzip to different folder to have multiple copy of program,  
then use [instance name](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini#name) inside prefetch.ini to distinguish them.

**Comment by mhtvsSFrpHdE** [comment]
Also, upload your ini file, I'll utllize them in debug.

**Comment by mhtvsSFrpHdE** [comment]
You've used `prefetch_verbose.exe`, and you should get a log file out there?

**Comment by manciuszz** [comment]
**chromium.ini**
```ini
[PrefetchFolder]
ChromiumUserdata=C:\\Users\\Admin\\AppData\\Local\\Chromium\\User Data

[Thread]
MaxThreadCount=0
RescanInterval=0
PrefetchInterval=720
ReadThreadPriority=LowestPriority
ReadBufferSize=1024

[MainWindow]
Position=<default>
Size=320,240
Resizable=true

[Instance]
Name=Chromium Prefetcher
StartToTray=true
MinimizeToTray=true
TrayMenuMinimalWidth=100
MaximumBlockCount=100
Font=<default>
FontSize=10
PrintOffset=1
ZoomLevel=100
Language=<default>
TranslateFolder=<default>

[CustomTrayMenu]
Chromium=\"D:\\Program Files\\Chromium\\chrome.exe\"
```

Make sure **prefetch.ini** and **prefetch.cache.ini** doesn't exist. Otherwise, it will use them.

Run command `prefetch_verbose.exe chromium.ini`

Created (full) output of **prefetch.log**:
```ini
LastKnownLocation BEGIN
    File: ../prefetch/Source/Global/global.cpp
    Function: init
    Line: 35
LastKnownLocation INLINE
    File: ../prefetch/Source/Global/global.cpp
    Function: init
    Line: 38
LastKnownLocation INLINE
    File: ../prefetch/Source/Global/global.cpp
    Function: init
    Line: 41
LastKnownLocation INLINE
    File: ../prefetch/Source/Global/global.cpp
    Function: init
    Line: 44
LastKnownLocation INLINE
    File: ../prefetch/Source/Translate/init_file.cpp
    Function: initFile
    Line: 198
```

No **cache.ini** has been created nor did the standby memory get filled. The process closed immediately upon launch.

Right now, my current solution is to use an AHK script to manage my prefetch configurations by replacing **prefetch.ini**. It gives me more flexibility than just making hard-copies.

---

Regardless of the current issue, The current pathing escaping mechanism is also very not user friendly and should be improved.

I'd love it if we could just use 
```ini
[PrefetchFolder]
ChromiumUserdata="C:\Users\Admin\AppData\Local\Chromium\User Data"
```
that way, windows users could use "Copy as Path" feature directly...

or
```ini
[PrefetchFolder]
ChromiumUserdata=C:/Users/Admin/AppData/Local/Chromium/User Data
```

**Comment by mhtvsSFrpHdE** [comment]
@manciuszz

**Path**  
According to this [stackoverflow answer](https://stackoverflow.com/questions/31143938/qsettings-what-is-the-way-to-read-path-value) by [Kuba hasn't forgotten Monica](https://stackoverflow.com/users/1329652/kuba-hasnt-forgotten-monica):

> Although backslash is a special character in INI files, most Windows applications don't escape backslashes () in file paths [...]
> QSettings always treats backslash as a special character and provides no API for reading or writing such entries.

This is what the documentation has to say about it. It is a polite way of saying "if some other code does it, they're not following the WINAPI spec and it's broken and we shouldn't have to deal with it". Pretty much your .ini files are broken.

If you wish to read them, you may need to provide your own backend for QSettings. Such a backend can be easily obtained by copying the one that comes as part of Qt, and modifying it not to perform escaping.

You'd need to investigate whether writing your own QTextCodec for this purpose and passing it to QSettings::setIniCodec would be sufficient. If sufficient, you wouldn't need to provide an entire backend.

<hr>

These above text basically says Qt QSettings ini reader refuse to support ini file with single backslash path.  
I noticed the problem in the very first version of C++ prefetch.  
Unless rewrite part or full of a QT component,  
to represent a backslash in ini file, user (either dev or end user) must escape it properly by another backslash.

You'll also notice that although this program use Qt, but it's not a typical GUI program.  
You do everything via command, and edit ini manually instead of a file dialog to pick folders.  
The current main window is just a console emulator to let you transfer texts into internal.  
Therefore, prefetch is a CLI program.

To improve that, you may use python + tkinter or something to create a UI wrapper.  
Setting editor could also be implemented by this way if you don't want to deal with ini manually.  
Or maybe write a patch for QSettings to let it support backslash.

There is similar relationship in software world, be like:

- 7z GUI and 7za, tar
- GitHub Desktop and git
- Windows file explorer and dir, ls

The project has no development team, I must choose the style of "do less to do more".
So the program have relative good API to let you write your own GUI or inject additional feature.
For example, compile as a console application and use python or something to send text to stdin interface.

The program crash directly with no error check is a side effect,
I simply not possible to predict any potential bug.

**Comment by mhtvsSFrpHdE** [comment]
## Crash reason
![image](https://user-images.githubusercontent.com/10773245/208439873-40a1865b-8b9a-4665-88ba-471f13684f71.png)
Log says last know position is line 198, source code says it doesn't find any available translate file,  
so program is ended by an "expected" unhandled exception.

Wiki page [Language](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini#language---optional) and [TranslateFolder](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini#translatefolder---optional) documented how program would look for a translate file.  
The program has no built-in hard coded UI string, e.g. English itself is also part of translate file,  
and will get from external just like how to get information from ini file.  
Even if you don't need, this folder is required to install on disk. It's not optional.  
You can delete other language file, but at least keep en_US files out there, that's how it works.

## Other ini problem
![image](https://user-images.githubusercontent.com/10773245/208442493-2e563e34-4853-411b-a12e-344df4936bcb.png)
Compare to a standard ini, you also suggested writing config keys what you don't need.  
Wiki page [Array](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini#array) documented how you clear a array:  
```
// Empty example
[ExcludeFolder]
[PriorityIncludePattern]
```
Notice that config key is still there.  
Actually, when I do these code, I assume there is a config key out there.  
I don't know what will happen if it's not there, never imagined before.  
It's kinda like...you'll try to get a not exist key from a python dictionary.  
It should crash directly, but if not, I also don't know what just happened. It's not under control.

For the same reason, when your ini doesn't contain:
```
[MainWindow]
Position=<default>
Size=320,240
Resizable=true
```
The code will still try to access `MainWindow`, `Position`, `Size`, `Resizable`.  
It doesn't have built-in default values. And it should crash when these key is accessed.  
Because [The program has no error detection](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini#prefetchini).

Your ini now should look like this:
```
[PrefetchFolder]
ChromiumUserdata=C:\\Users\\Admin\\AppData\\Local\\Chromium\\User Data

[ExcludeFolder]
[PriorityIncludePattern]
[AfterPrefetch]

[Thread]
MaxThreadCount=0
RescanInterval=0
PrefetchInterval=720
ReadThreadPriority=LowestPriority
ReadBufferSize=1024

[MainWindow]
Position=<default>
Size=320,240
Resizable=true

[Instance]
Name=Chromium Prefetcher
StartToTray=true
MinimizeToTray=true
TrayMenuMinimalWidth=100
MaximumBlockCount=100
Font=<default>
FontSize=10
PrintOffset=1
ZoomLevel=100
Language=<default>
TranslateFolder=<default>

[MainWindow]
Position=<default>
Size=320,240
Resizable=true

[CustomTrayMenu]
Chromium=\"D:\\Program Files\\Chromium\\chrome.exe\"
```

This ini successfully booted with no crash. But bug still exist.  
Program will write `chromium.ini` cache to `prefetch.cache.ini`, instead of `chromium.cache.ini`.  
You still need to duplicate entire program folder instead of ahk switch.  
Because if `prefetch.cache.ini` exist, 2nd instance will ignore folder settings and use cache ini directly.  
So if you have 3 instance and start 3 times, 2nd and 3rd actually inheritances 1st folder settings.

**Comment by mhtvsSFrpHdE** [comment]
![image](https://user-images.githubusercontent.com/10773245/208450135-ffcf7efe-161a-4a3d-a2c6-4e0e9378722d.png)
LOL an extra equal sign

**Comment by mhtvsSFrpHdE** [comment]
[4.0.4](https://github.com/mhtvsSFrpHdE/prefetch/releases) is available now.

Also, if you have done python GUI works, you can share your code,  
so everyone can benefit from it, aka a better config editor / folder picker.

For other feedback, create new issue.

Happy prefetching!

**Comment by mhtvsSFrpHdE** [comment]
@manciuszz I provided a wrong ini example, `[MainWindow]` group duplicated twice.  
The one does exist in your ini, but I accidentally didn't see it.

If you have copied this example, you may remove one of them,  
although this should be harmless since you've not modified it to other than default value.

**Comment by manciuszz** [comment]
@mhtvsSFrpHdE I'm actually still unable to prefetch files using `prefetch.exe chromium.ini` command line on version `4.0.4`.

https://user-images.githubusercontent.com/2539661/209013395-2452e687-0844-4a47-a42a-f23a499938e5.mp4

**Comment by mhtvsSFrpHdE** [comment]
@manciuszz This time `prefetch_verbose.exe chromium.ini` and `prefetch.log`?

Your ini boot success with 4.0.4 in my computer(`prefetch
exe chromium.ini`), Windows 10 22H2, tested under Windows Terminal, PowerShell, and traditional cmd.

**Comment by mhtvsSFrpHdE** [comment]
@manciuszz Confirmed, later will look at it.  
To reproduce this bug, I need to delete `prefetch.ini` first and only put `chromium.ini`.

In 4.0.4, I only verified command line arguments is passed, but forget to check if ini truly loaded.

**Comment by mhtvsSFrpHdE** [comment]
@manciuszz 8480b8b8b76bc948241ea589b573627910ffe097 Just busted two more extra equal sign...😰  
I hope they will not be endless😰

[4.0.5](https://github.com/mhtvsSFrpHdE/prefetch/releases) is available now.

**Comment by manciuszz** [comment]
I can confirm version 4.0.5 works as intended.

It would have been nice to have the `*.cache.ini` be created near the config file though. Right now, a command like

`prefetch.exe ../../Configs/chromium/prefetch.ini`

would load the `prefetch.ini` properly, but the `prefetch.cache.ini` would be located near the `prefetch.exe`.

This creates an inconsistency where the config files are in two different places. 
Unfortunately, a symbolic link doesn't work with `prefetch.exe`, so we can't use it to make a workaround - a hard link does work though.

**Comment by mhtvsSFrpHdE** [comment]
### \*.ini

When start, type setting file name after `prefetch.exe` to load different settings.  
If no ini provided, default is `prefetch.ini`.  
All ini should place at same folder with `prefetch.exe` see details below:

```
>prefetch.exe iexplore.ini

new QSettings(QCoreApplication::applicationDirPath() + "/" + <your value goes here>, QSettings::IniFormat);
```
<hr>
  
[ini document](https://github.com/mhtvsSFrpHdE/prefetch/wiki/prefetch.ini#ini) clearly says all ini should place at same folder with `prefetch.exe`, and provided internal code example to help you understand what happened out there.

I'm not saying put ini in other folder is bad  
or refuse to support say something "by design",  
but unfortunately you have to code this feature yourself,  
and send a merge request.  
Either command line argument parser and file name conversation is required to rewrite.
